### ISSUE TITLE
Intended usage of /callback

### ISSUE THREAD

**Issue by micimize** [octokit/oauth-app.js#269]
Hi – I was wondering what the intended usage of `/api/github/oauth/callback` is, beyond demonstration purposes? Is an implementor expected to override the route, or just implement a separate one?

Along those lines, I was thinking it'd be good to provide a callback mechanism for overriding the route instead.

**Comment by baoshan** [comment]
Where do you need the access token? In the browser or in the server side?

When the access token is needed by your server-side app, I think you can specify your own redirect url instead of `/api/github/oauth/callback` (with the current implementation serving as a reference). You can also benefit from redirecting users to a more semantic url such as `/dashboard` rather than `/api/github/oauth/callback`.

[auth-oauth-user-client](https://github.com/octokit/auth-oauth-user-client.js) should be your choice when the access token will be used in the browser. The [initial version (not merged)](https://github.com/octokit/auth-oauth-user-client.js/tree/initial-version) does not rely on `/api/github/oauth/callback`.

**Comment by micimize** [comment]
ok – that is helpful thanks. We will use the token on the server with a custom redirect uri
